# Generated by Django 5.2.17 on 2026-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_level',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='certificate_information',
            field=models.TextField(blank=True, help_text='CEFR / Multilevel certificate, teaching certificates, etc.'),
        ),
    ]
