# Generated by Django 5.2.17 on 2026-10-05 17:27

from django.db import migrations, models


def teachers_to_students(apps, schema_editor):
    """The teacher role was removed together with the course system."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="teacher").update(role="student")
    apps.get_model("auth", "Group").objects.filter(name="Teachers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.RunPython(teachers_to_students, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], db_index=True, default='student', max_length=16),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
