# Generated by Django 5.2.17 on 2026-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English')], default='uz', max_length=8),
        ),
    ]
