# Generated by Django 5.2.17 on 2026-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=80, unique=True)),
                ('ipa', models.CharField(blank=True, max_length=80, verbose_name='Pronunciation (IPA)')),
                ('part_of_speech', models.CharField(blank=True, max_length=30)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, help_text='CEFR level, e.g. B2', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
