# Generated by Django 5.2.17 on 2026-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingevaluation',
            name='scale',
        ),
        migrations.AlterField(
            model_name='writingevaluation',
            name='coherence_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Coherence and organisation'),
        ),
        migrations.AlterField(
            model_name='writingevaluation',
            name='grammar_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Grammar'),
        ),
        migrations.AlterField(
            model_name='writingevaluation',
            name='task_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Task completion'),
        ),
        migrations.AlterField(
            model_name='writingevaluation',
            name='vocabulary_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Vocabulary'),
        ),
    ]
