# Generated by Django 5.2.17 on 2026-10-05 16:02

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('ielts', 'IELTS'), ('multilevel', 'Multilevel / CEFR')], db_index=True, default='ielts', max_length=16)),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], db_index=True, max_length=16)),
                ('level', models.CharField(blank=True, choices=[('', 'Mixed / any level'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=2)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Minutes (0 = untimed)')),
                ('audio', models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.listening_audio_path, validators=[core.validators.FileValidator('audio')])),
                ('transcript', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('passage', models.TextField(blank=True, help_text='Reading passage text (Reading only)')),
                ('audio', models.FileField(blank=True, help_text='Optional per-section audio (Listening)', storage=core.storage.private_storage, upload_to=core.storage.listening_audio_path, validators=[core.validators.FileValidator('audio')])),
                ('transcript', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='exams.mockexam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Question number')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('matching', 'Matching'), ('sentence_completion', 'Sentence completion'), ('summary_completion', 'Summary completion'), ('short_answer', 'Short answer')], default='multiple_choice', max_length=32)),
                ('prompt', models.TextField(help_text='Question text. For completion use ___ for the gap.')),
                ('correct_answer', models.CharField(blank=True, help_text='For TFNG/YNNG: TRUE/FALSE/NOT GIVEN. For matching: the option label (e.g. C). For completion/short answer: accepted answers separated by | (e.g. 1990|nineteen ninety). Multiple choice uses the options marked correct.', max_length=500)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('explanation', models.TextField(blank=True, help_text='Shown to the student after submission')),
                ('exam', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.mockexam')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exampart')),
            ],
            options={
                'ordering': ['part__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C… or i, ii, iii…', max_length=8)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1 — Interview'), (2, 'Part 2 — Cue card (long turn)'), (3, 'Part 3 — Discussion')], default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.TextField()),
                ('cue_card_points', models.TextField(blank=True, help_text='Part 2: one bullet point per line')),
                ('preparation_time', models.PositiveIntegerField(default=5, help_text='Seconds')),
                ('speaking_time', models.PositiveIntegerField(default=30, help_text='Seconds')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_questions', to='exams.mockexam')),
            ],
            options={
                'ordering': ['part', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('ielts_task1', 'IELTS Writing Task 1'), ('ielts_task2', 'IELTS Writing Task 2'), ('multilevel', 'Multilevel Writing')], max_length=16)),
                ('topic', models.TextField(help_text='The question / prompt the student must answer')),
                ('instructions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Chart/diagram for Task 1', upload_to=core.storage.writing_image_path, validators=[core.validators.FileValidator('image')])),
                ('minimum_word_count', models.PositiveIntegerField(default=150)),
                ('time_limit', models.PositiveIntegerField(default=20, help_text='Suggested minutes for this task')),
                ('level', models.CharField(blank=True, choices=[('', 'Mixed / any level'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=2)),
                ('is_published', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='exams.mockexam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['section', 'exam_type', 'is_published'], name='exams_mocke_section_d0610c_idx'),
        ),
    ]
