# Generated by Django 5.2.17 on 2026-10-05 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mockexam',
            name='exams_mocke_section_d0610c_idx',
        ),
        migrations.RemoveField(
            model_name='mockexam',
            name='exam_type',
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='part',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Part 1 — Interview'), (2, 'Part 2 — Long turn'), (3, 'Part 3 — Argument / discussion')], default=1),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='task_type',
            field=models.CharField(choices=[('task1_1', 'Task 1.1 — Informal letter'), ('task1_2', 'Task 1.2 — Formal letter'), ('task2', 'Task 2 — Essay')], default='task2', max_length=16),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['section', 'is_published'], name='exams_mocke_section_7de524_idx'),
        ),
    ]
