# Generated by Django 5.2.17 on 2026-10-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_multilevel_task_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('', 'Mixed / any level'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=2)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listening', models.ForeignKey(limit_choices_to={'section': 'listening'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.mockexam')),
                ('reading', models.ForeignKey(limit_choices_to={'section': 'reading'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.mockexam')),
                ('speaking', models.ForeignKey(limit_choices_to={'section': 'speaking'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.mockexam')),
                ('writing', models.ForeignKey(limit_choices_to={'section': 'writing'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exams.mockexam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
