# Generated by Django 5.2.17 on 2026-10-06 10:12

import core.storage
import core.validators
from django.db import migrations, models


def renumber_parts(apps, schema_editor):
    """Old 3-part numbering -> Multilevel 4-part numbering (1.1, 1.2, 2, 3)."""
    SpeakingQuestion = apps.get_model("exams", "SpeakingQuestion")
    SpeakingQuestion.objects.filter(part=3).update(part=4)  # old Part 3 -> Part 3 (value 4)
    SpeakingQuestion.objects.filter(part=2).update(part=3)  # old Part 2 long turn -> Part 2 (value 3)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_fullmock'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Part 1.2: the two pictures to compare (one combined image)', upload_to=core.storage.writing_image_path, validators=[core.validators.FileValidator('image')]),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='maximum_word_count',
            field=models.PositiveIntegerField(blank=True, help_text='Upper end of the target range (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='cue_card_points',
            field=models.TextField(blank=True, help_text="Part 2: one prompt per line. Part 3: arguments, one per line, starting with 'For:' or 'Against:'"),
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='part',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Part 1.1 — Personal questions'), (2, 'Part 1.2 — Picture comparison'), (3, 'Part 2 — Long turn'), (4, 'Part 3 — Argument')], default=1),
        ),
        migrations.RunPython(renumber_parts, migrations.RunPython.noop),
    ]
