# Generated by Django 5.2.17 on 2026-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_speakingquestion_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampart',
            name='summary',
            field=models.CharField(blank=True, help_text='Short topic shown on the mock card', max_length=80),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='summary',
            field=models.CharField(blank=True, help_text='Short topic shown on the mock card (Writing: the Part 1 situation)', max_length=80),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='summary',
            field=models.CharField(blank=True, help_text='Topic of this part for the mock card (set it on the first question)', max_length=80),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='summary',
            field=models.CharField(blank=True, help_text="Short line for the mock card, e.g. 'informal letter · to friend'", max_length=80),
        ),
    ]
