# Generated by Django 5.2.17 on 2026-10-07 05:54

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exampart_summary_mockexam_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampart',
            name='image',
            field=models.ImageField(blank=True, help_text='Map / diagram for labelling questions', upload_to=core.storage.writing_image_path, validators=[core.validators.FileValidator('image')]),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('matching', 'Matching'), ('sentence_completion', 'Sentence completion'), ('summary_completion', 'Summary completion'), ('short_answer', 'Short answer'), ('map_labelling', 'Map / diagram labelling')], default='multiple_choice', max_length=32),
        ),
    ]
