# Generated by Django 5.2.17 on 2026-10-07 06:19

from django.db import migrations, models


def to_cefr_types(apps, schema_editor):
    """Map the old IELTS-style types onto the Multilevel (CEFR) set."""
    Question = apps.get_model("exams", "Question")
    Question.objects.filter(question_type__in=["sentence_completion", "summary_completion", "short_answer"]) \
        .update(question_type="gap_filling")
    for q in Question.objects.filter(question_type="yes_no_not_given"):
        q.correct_answer = {"YES": "TRUE", "NO": "FALSE"}.get(q.correct_answer.upper(), q.correct_answer.upper())
        q.question_type = "true_false_not_given"
        q.save(update_fields=["question_type", "correct_answer"])
    Question.objects.filter(question_type="matching", prompt__icontains="paragraph").update(question_type="headings")


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exampart_image_alter_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampart',
            name='cefr_part',
            field=models.CharField(blank=True, default='', help_text='Which official Multilevel part this is (sets the allowed question types)', max_length=4, verbose_name='CEFR part'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Gap filling: accepted answers separated by | (e.g. 1990|nineteen ninety). True/False/Not Given: TRUE, FALSE or NOT GIVEN. Matching / headings / map: the option label (e.g. C). Multiple choice uses the option marked correct.', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('gap_filling', 'Gap filling (one word / number)'), ('multiple_choice', 'Multiple choice'), ('true_false_not_given', 'True / False / Not Given'), ('matching', 'Matching (statements / speakers)'), ('headings', 'Matching headings'), ('map_labelling', 'Map labelling')], default='gap_filling', max_length=32),
        ),
        migrations.RunPython(to_cefr_types, migrations.RunPython.noop),
    ]
