# Generated by Django 5.2.17 on 2026-10-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exampart_cefr_part_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(help_text='Question text. For a gap inside the part text just write e.g. "Gap 1".'),
        ),
    ]
