# Generated by Django 5.2.17 on 2026-10-08 12:01

from django.db import migrations, models


def forwards(apps, schema_editor):
    """The Uzbek Multilevel exam says "No Information", not "Not Given"."""
    Question = apps.get_model("exams", "Question")
    ExamPart = apps.get_model("exams", "ExamPart")
    Answer = apps.get_model("results", "Answer")
    Question.objects.filter(question_type="true_false_not_given", correct_answer__in=["NOT GIVEN", "NG"]).update(
        correct_answer="NO INFORMATION")
    Answer.objects.filter(question__question_type="true_false_not_given",
                          answer__in=["NOT GIVEN", "NG"]).update(answer="NO INFORMATION")
    for part in ExamPart.objects.filter(title__icontains="not given") | ExamPart.objects.filter(
            instructions__icontains="not given"):
        part.title = part.title.replace("Not Given", "No Information").replace("NOT GIVEN", "NO INFORMATION")
        part.instructions = part.instructions.replace("NOT GIVEN", "NO INFORMATION").replace(
            "Not Given", "No Information")
        part.save(update_fields=["title", "instructions"])


def backwards(apps, schema_editor):
    Question = apps.get_model("exams", "Question")
    Answer = apps.get_model("results", "Answer")
    Question.objects.filter(correct_answer="NO INFORMATION").update(correct_answer="NOT GIVEN")
    Answer.objects.filter(answer="NO INFORMATION").update(answer="NOT GIVEN")


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_question_prompt'),
        ('results', '0006_examattempt_drafts_examattempt_drafts_saved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Gap filling: accepted answers separated by | (e.g. 1990|nineteen ninety). True/False/No Information: TRUE, FALSE or NO INFORMATION. Matching / headings / map: the option label (e.g. C). Multiple choice uses the option marked correct.', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('gap_filling', 'Gap filling (one word / number)'), ('multiple_choice', 'Multiple choice'), ('true_false_not_given', 'True / False / No Information'), ('matching', 'Matching (statements / speakers)'), ('headings', 'Matching headings'), ('map_labelling', 'Map labelling')], default='gap_filling', max_length=32),
        ),
        migrations.RunPython(forwards, backwards),
    ]
