# Generated by Django 5.2.17 on 2026-10-05 16:02

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=core.storage.course_thumbnail_path, validators=[core.validators.FileValidator('image')])),
                ('category', models.CharField(choices=[('general_english', 'General English'), ('ielts', 'IELTS'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('reading', 'Reading'), ('listening', 'Listening'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('multilevel', 'Multilevel')], db_index=True, default='general_english', max_length=32)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('ielts', 'IELTS'), ('multilevel', 'Multilevel / CEFR')], db_index=True, default='intermediate', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_free', models.BooleanField(default=True)),
                ('duration', models.CharField(blank=True, help_text="e.g. '6 weeks' or '12 hours'", max_length=60)),
                ('language', models.CharField(default='English', max_length=60)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.lesson_video_path, validators=[core.validators.FileValidator('video')])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo link (used if no video file is uploaded)')),
                ('material', models.FileField(blank=True, storage=core.storage.private_storage, upload_to=core.storage.lesson_material_path, validators=[core.validators.FileValidator('document')], verbose_name='PDF / material')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('is_free_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('last_accessed_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.courselesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('watch_progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent of the video watched', max_digits=5)),
                ('last_watched_position', models.FloatField(default=0, help_text='Seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.courselesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_lesson_progress')],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment'),
        ),
    ]
