# Generated by Django 5.2.17 on 2026-10-05 16:02

import core.storage
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(storage=core.storage.private_storage, upload_to=core.storage.speaking_recording_path, validators=[core.validators.FileValidator('recording')])),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('duration', models.FloatField(default=0, help_text='Seconds (reported by the recorder)')),
                ('processing_status', models.CharField(choices=[('pending', 'Uploaded'), ('transcribing', 'Transcribing'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to='results.examattempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speaking_submissions', to='exams.mockexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='exams.speakingquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question__part', 'question__order', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=100)),
                ('stt_provider', models.CharField(blank=True, max_length=32)),
                ('stt_model', models.CharField(blank=True, max_length=100)),
                ('scale', models.CharField(max_length=16)),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fluency_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Fluency and coherence')),
                ('vocabulary_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Lexical resource')),
                ('grammar_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Grammatical range and accuracy')),
                ('pronunciation_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pronunciation_assessed', models.BooleanField(default=False)),
                ('cefr_level', models.CharField(blank=True, max_length=16)),
                ('fluency_feedback', models.TextField(blank=True)),
                ('coherence_feedback', models.TextField(blank=True)),
                ('vocabulary_feedback', models.TextField(blank=True)),
                ('grammar_feedback', models.TextField(blank=True)),
                ('pronunciation_feedback', models.TextField(blank=True)),
                ('detailed_feedback', models.TextField(blank=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='speaking.speakingsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='speakingsubmission',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_speaking_per_question'),
        ),
    ]
