# Generated by Django 5.2.17 on 2026-10-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='results.examattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='exams.writingtask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=100)),
                ('scale', models.CharField(choices=[('ielts', 'IELTS band (0–9)'), ('multilevel', 'Multilevel (0–75)')], max_length=16)),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('task_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Task achievement / response')),
                ('coherence_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Coherence and cohesion')),
                ('vocabulary_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Lexical resource')),
                ('grammar_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Grammatical range and accuracy')),
                ('cefr_level', models.CharField(blank=True, max_length=16)),
                ('task_feedback', models.TextField(blank=True)),
                ('coherence_feedback', models.TextField(blank=True)),
                ('vocabulary_feedback', models.TextField(blank=True)),
                ('grammar_feedback', models.TextField(blank=True)),
                ('detailed_feedback', models.TextField(blank=True)),
                ('grammar_mistakes', models.JSONField(blank=True, default=list)),
                ('vocabulary_mistakes', models.JSONField(blank=True, default=list)),
                ('suggested_corrections', models.JSONField(blank=True, default=list)),
                ('weak_sentences', models.JSONField(blank=True, default=list)),
                ('strong_sentences', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='writing.writingsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='writingsubmission',
            constraint=models.UniqueConstraint(fields=('attempt', 'task'), name='unique_writing_per_task'),
        ),
    ]
